import type { LiaisonDefinition, LiaisonType } from '../types';

export const LIAISON_DEFS: Record<LiaisonType, LiaisonDefinition> = {
  pivot: {
    type: 'pivot',
    name: 'Pivot',
    dof: 1,
    description: '1 rotation (Rz)',
    viewCount: 3,
  },
  glissiere: {
    type: 'glissiere',
    name: 'Glissière',
    dof: 1,
    description: '1 translation (Tz)',
    viewCount: 3,
  },
  pivot_glissant: {
    type: 'pivot_glissant',
    name: 'Pivot glissant',
    dof: 2,
    description: '1 rotation + 1 translation',
    viewCount: 3,
  },
  rotule: {
    type: 'rotule',
    name: 'Sphérique',
    dof: 3,
    description: '3 rotations (Rx, Ry, Rz)',
    viewCount: 1,
  },
  encastrement: {
    type: 'encastrement',
    name: 'Encastrement',
    dof: 0,
    description: '0 degrés de liberté',
    viewCount: 1,
  },
  helicoidale: {
    type: 'helicoidale',
    name: 'Hélicoïdale',
    dof: 1,
    description: '1 rotation + 1 translation liées',
    viewCount: 3,
  },
  rotule_doigt: {
    type: 'rotule_doigt',
    name: 'Sphérique à doigt',
    dof: 2,
    description: '2 rotations (Rx, Ry)',
    viewCount: 1,
  },
  appui_plan: {
    type: 'appui_plan',
    name: 'Appui plan',
    dof: 3,
    description: '2 translations + 1 rotation',
    viewCount: 3,
  },
  lineaire_annulaire: {
    type: 'lineaire_annulaire',
    name: 'Sphère-cylindre',
    dof: 4,
    description: '3 rotations + 1 translation',
    viewCount: 3,
  },
  lineaire_rectiligne: {
    type: 'lineaire_rectiligne',
    name: 'Cylindre-plan',
    dof: 4,
    description: '2 rotations + 2 translations',
    viewCount: 3,
  },
  ponctuelle: {
    type: 'ponctuelle',
    name: 'Sphère-plan',
    dof: 5,
    description: '3 rotations + 2 translations',
    viewCount: 3,
  },
  bati: {
    type: 'bati',
    name: 'Bâti',
    dof: 0,
    description: 'Solide fixe (référentiel)',
    viewCount: 1,
  },
  engrenage_ext: {
    type: 'engrenage_ext',
    name: 'Engrenage extérieur',
    dof: 0,
    description: 'Engrenage à denture extérieure',
    viewCount: 2,
  },
  engrenage_int: {
    type: 'engrenage_int',
    name: 'Engrenage intérieur',
    dof: 0,
    description: 'Engrenage à denture intérieure',
    viewCount: 2,
  },
  engrenage_conique: {
    type: 'engrenage_conique',
    name: 'Engrenage conique',
    dof: 0,
    description: 'Engrenage à denture conique',
    viewCount: 2,
  },
  roue_vis_sans_fin: {
    type: 'roue_vis_sans_fin',
    name: 'Roue et vis sans fin',
    dof: 0,
    description: 'Roue dentée engrenant avec une vis sans fin',
    viewCount: 2,
  },
  transmission_poulie_courroie: {
    type: 'transmission_poulie_courroie',
    name: 'Transmission par poulie courroie',
    dof: 0,
    description: 'Deux poulies reliées par une courroie',
    viewCount: 2,
  },
  transmission_pignons_chaine: {
    type: 'transmission_pignons_chaine',
    name: 'Transmission par pignons et chaîne',
    dof: 0,
    description: 'Deux pignons reliés par une chaîne',
    viewCount: 2,
  },
};

export const LIAISON_LIST = Object.values(LIAISON_DEFS).filter((d) => d.type !== 'bati');
export const BATI_DEF = LIAISON_DEFS.bati;
